<a href="https://colab.research.google.com/github/karinfaraujo/python-projects/blob/main/Python_para_ML_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Python para Machine Learning - 7**

##**Atribuição de Variáveis**

In [ ]:
# minhas características
meunome = 'Karin'
minhaidade = 31

OBS.: O **hashtag #** na frente de uma linha torna ela um **comentário**, pois o interpretador ignora tudo que vem depois dela.

In [ ]:
print(meunome)
print(minhaidade)

Karin
31


In [ ]:
minha_idade = 31

Não é possível atribuir variáveis com nomes começando com números, nem com espaços no nome ou com aspas.

In [ ]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



## **Primeiras Funções** <a name="prim"></a>

A função **len**, retorna o tamanho de uma string (e de outros tipos de objetos também).

A função **type**, retorna o tipo do objeto na variável de entrada.

A função **round**, arredonda um número de acordo com as casas decimas desejadas.

E a função **help**, retorna a documentação da função inserida como entrada.

In [ ]:
len(meunome)

5

Não só no Python, mas em programação em geral, sempre precisamos controlar o tipo das variáveis que utilizamos.

In [ ]:
minha_idade = '33'
type(minha_idade)

str

Usando a função **int** para converter a variável em formato string para o formato inteiro.

In [ ]:

minha_idade = int(minha_idade)
type(minha_idade)

int

##**Operadores Aritméticos**

Confira na tabela abaixo como funcionam os operadores aritméticos em Python.

Em especial, veja que a sintaxe da exponenciação não é feita através do sinal '^'.

| Operator     | Name           | Description                                            |
|--------------|----------------|--------------------------------------------------------|
| ``a + b``    | Adiçao       | Soma entre ``a`` e ``b``                                 |
| ``a - b``    | Subtração    | Diferença entre ``a`` e ``b``                          |
| ``a * b``    | Multiplicação | Produto entre ``a`` e ``b``                             |
| ``a / b``    | Divisão  | Divisão usual entre ``a`` e ``b``                            |
| ``a // b``   | Divisão inteira | A divisão entre ``a`` e ``b``, removendo as partes decimais |
| ``a % b``    | Resto da divisão        | O resto da divisão inteira de ``a`` por ``b``     |
| ``a ** b``   | Exponenciação | ``a`` elevado a ``b``                     |
| ``-a``       | Negação       | O negativo de ``a``                                  |

In [ ]:
a = 2
b = 5

print('Soma:', a + b)
print('Dif:', a - b)
print('Div:', a / b)
print('Mult:', a * b)

print('Exponenciação:', a ** b)
print('Resto da divisao:', b % a)
print('Divisao Inteira:', b // a)

Soma: 7
Dif: -3
Div: 0.4
Mult: 10
Exponenciação: 32
Resto da divisao: 1
Divisao Inteira: 2


##**Comparações e Booleanos**

Quando comparamos objetos em Python é como se estivéssemos fazendo uma pergunta a ele. Duas variáveis são iguais? Uma é maior que a outra?

E a resposta é um objeto do tipo **booleano**, que é indicado por **True** ou **False**, indicando, respectivamente, se a resposta é verdadeira ou falsa.

In [ ]:
a < b

True

In [ ]:
b < a

False

In [ ]:
type (a<b)

bool

In [ ]:
# Conectivos Lógicos

True and False

False

In [ ]:
True or False

True

In [ ]:
not False

True

In [ ]:
not True

False

In [ ]:
a == b

False

In [ ]:
(a == b) or (a < b)

True

In [ ]:
(a <= b)

True

In [ ]:
(a >= b)

False

In [ ]:
a == b

False

In [ ]:
a != b

True

##**Condicional IF-ELSE**

Temos a versão IF ELSE, e a versão IF ELIF ELSE.

Note que é possível utilizar o ELIF várias vezes se necessário.

No espaço de condição, o Python espera um objeto booleano. Se for True, ele executa, se for False, segue adiante.

Note também a estrutura de identação do Python. Aqui não usamos (), [] ou {} para estipular o que deve ser executado nas condicionais. Simplesmente colocamos o código que deve ser executado na linha seguinte, mas identado. Em geral, se utiliza o espaço de **1 tab**.

In [ ]:
if a > b:
    print('A condição foi TRUE')
else:
    print('A condição foi FALSE')

A condição foi FALSE


In [ ]:
if a > b:
    print('A condição foi TRUE')
    print('A condição foi TRUE')
    print('A condição foi TRUE')
    print('A condição foi TRUE')
    print('A condição foi TRUE')
    print('A condição foi TRUE')
else:
    print('A condição foi FALSE')
    print('A condição foi FALSE')
    print('A condição foi FALSE')

A condição foi FALSE
A condição foi FALSE
A condição foi FALSE


In [ ]:
if a < b:
    print('A condição foi TRUE')
    print('A condição foi TRUE')
    print('A condição foi TRUE')
    print('A condição foi TRUE')
    print('A condição foi TRUE')
    print('A condição foi TRUE')
else:
    print('A condição foi FALSE')
    print('A condição foi FALSE')
    print('A condição foi FALSE')

A condição foi TRUE
A condição foi TRUE
A condição foi TRUE
A condição foi TRUE
A condição foi TRUE
A condição foi TRUE


Equação do Segundo Grau:

$$ a x^2 + bx + c = 0 $$

In [ ]:
from re import X
a, b, c = 1, 2, -1


delta = b**2 - 4*a*c

delta

if delta > 0:
    x1 = (-b + delta**(1/2))/(2*a)
    x2 = (-b - delta**(1/2))/(2*a)
    print('As raízes são {} e {}'.format(x1,x2))
elif delta == 0:
    x = -b/(2*a)
    print('A raíz é {}'.format(x))
else:
    print('A equação não possui raízes reais')

As raízes são 0.41421356237309515 e -2.414213562373095


In [ ]:
from re import X
a, b, c = 1, 2, 1


delta = b**2 - 4*a*c

delta

if delta > 0:
    x1 = round((-b + delta**(1/2))/(2*a),3)
    x2 = round((-b - delta**(1/2))/(2*a),3)
    print('As raízes são {} e {}'.format(x1,x2))
elif delta == 0:
    x = round(-b/(2*a),3)
    print('A raíz é {}'.format(x))
else:
    print('A equação não possui raízes reais')

A raíz é -1.0


##**Definição de Funções**

Uma função é um recurso para não precisarmos repetir o mesmo código desnecessariamente. Assim como as funções da matemática, sua tarefa é transformar um input, uma entrada, uma coleção de variáveis, em uma saída, um output.

Da mesma maneira que na estrutura de condicionais, o conteúdo de uma função fica nas linhas seguintes sendo indicados pela **indentação** do código.

In [ ]:
def MinhaFuncao(n_asteriscos):
    print('*' * n_asteriscos)
    print('Karin')
    print('*' * n_asteriscos)

In [ ]:
MinhaFuncao(n_asteriscos = 20)

********************
Karin
********************


In [ ]:
def Bhaskara(a, b, c):
    delta = b**2 - 4*a*c

    if delta > 0:
        x1 = (-b + delta**(1/2))/(2*a)
        x2 = (-b - delta**(1/2))/(2*a)
        print('As raízes são {} e {}'.format(x1,x2))
    elif delta == 0:
        x = -b/(2*a)
        print('A raíz é {}'.format(x))
    else:
        print('A equação não possui raízes reais')

In [ ]:
Bhaskara(a = 1, b = 2, c = -1)

As raízes são 0.41421356237309515 e -2.414213562373095


##**Listas**

In [ ]:
lista = ['Karin', 31, Bhaskara, [['A', 'B'], 2, 3, 4]]

In [ ]:
lista

['Karin', 31, <function __main__.Bhaskara(a, b, c)>]

In [ ]:
lista[2](a = 1, b = 2, c = -1)

As raízes são 0.41421356237309515 e -2.414213562373095


In [ ]:
lista[3][0][1]

'B'

In [ ]:
lista2 = list('Karin')

In [ ]:
lista2[-1]

'n'

In [ ]:
lista2[:2]    #Intervalos Abertos

['K', 'a']

##**Importação de Bibliotecas**

In [ ]:
from math import pi

In [ ]:
pi

3.141592653589793

In [ ]:
from math import pi, sqrt

In [ ]:
sqrt(5)

2.23606797749979

In [ ]:
import math

In [ ]:
math.ceil(2.3)

3

In [ ]:
import math as m

In [ ]:
m.ceil(2.3)

3

##**A Biblioteca Numpy**

Numpy é a biblioteca mais popular do python para se trabalhar com arrays.

Arrays são conjuntos de valores, que podem ser n-dimensionais e são feitos para se trabalhar com álgebra linear.

Geralmente, um número apenas, um ponto, é um array de dimensão 0.

Uma lista de valores é um array de dimensão 1.

Uma matriz de valores é uma array de dimensão 2.

Um tensor de valores é um array de dimensão 3.


In [ ]:
import numpy as np

In [ ]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [ ]:
3 * np.array([1, 2, 3, 4])

array([ 3,  6,  9, 12])

In [ ]:
3 * [1, 2, 3, 4]

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [ ]:
[1, 2, 3, 4] + [5, 6, 7]

[1, 2, 3, 4, 5, 6, 7]

In [ ]:
2.2 + np.array ([1, 2, 3, 4])

array([3.2, 4.2, 5.2, 6.2])

In [ ]:
np.array ([[1, 2, 3, 4], [3, 2, 4, 46]])

array([[ 1,  2,  3,  4],
       [ 3,  2,  4, 46]])

In [ ]:
np.arange(10,31)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30])

In [ ]:
np.arange(10,31,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
np.random.choice([1, 2, 3, 4, 5], size = 3)

array([2, 3, 1])

In [ ]:
x = np.arange(1, 213)
np.random.choice(x, size = 4)

array([ 72, 114, 122, 125])

In [ ]:
np.all([True, True, True, True, True])

True

In [ ]:
np.all([True, False, True, True, True])

False

In [ ]:
np.any([True, False, True, True, True])

True

In [ ]:
np.any([True, False, False, False, False])

True

##**Funções Importantes**

O comando **input** serve para se comunicar com o usuário enquanto se executa um programa.


In [ ]:
x = input('Digite o seu nome: ')

Digite o seu nome:  Karin


In [ ]:
print(x)

 Karin


In [ ]:
y = input('Digite a sua idade: ')
print('\nA idade declarada foi {}'.format(y))

Digite a sua idade:  31

A idade declarada foi  31


Os inputs são sempre no format string. Se quisermos usá-lo numericamente, temos que converter as entradas adequadamanente. Em geral usamos a função **int** para inteiros ou **float** para números reais. Você pode usar a função float para números que são inteiros também.

In [ ]:
y = int(input('Digite a sua idade '))

print('\nSe você já fez aniversário esse ano, seu ano de nascimento foi {}.'.format(2023 - y))

Digite a sua idade  32

Se você já fez aniversário esse ano, seu ano de nascimento foi 1991.


A função **range** cria um objeto capaz de gerar listas de valores entre dois números.

Ela não gera a lista em si, mas um gerador de lista pra quando ela for utilizada.

**Essa função trabalha com intervalos semi-abertos do tipo [ , )**.

In [ ]:
range(4)

range(0, 4)

Para listar os valores da função range, utilize o comando **list**.

In [ ]:
list(range(4))

[0, 1, 2, 3]

Use-a com dois parâmetros para definir o começo e o fim da lista. Note que o primeiro valor é incluido, mas o último não, pois o intervalo dela é semi-aberto.

In [ ]:
list(range(3, 10))


[3, 4, 5, 6, 7, 8, 9]

Pode-se usar ainda um terceiro parâmetro, que é o passo da lista. Ele deve ser inteiro e representa o salto de um número para o outro.

In [ ]:
list(range(2, 21, 2))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
list(range(10, 101, 10))

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

A função **list** também pode ser utilizada para quebrar uma string em caracteres dentro de uma lista.

In [ ]:
list('Python')

['P', 'y', 't', 'h', 'o', 'n']

##**Iteradores FOR e WHILE**

Utilizamos a estrutura de repetição **FOR** sempre que desejamos repetir um certo pedaço de código, com alterações ou não, por um número pre-determinado de vezes.

In [ ]:
for i in [1,2,3,4,5]:
    print(i**2)

1
4
9
16
25


In [ ]:
for i in [1,2,3,4,5]:
    print(np.random.choice(x, size = 4))

[ 16 174  31 181]
[ 67  31  21 156]
[ 75  30  10 167]
[153 202 192 166]
[181  59 193  73]


In [ ]:
for i in np.arange(0,10):
    print(np.random.choice(x, size = 4))

[176 174 122  94]
[140 201 151  35]
[114  95 118 126]
[182  32 119  17]
[197 162  83  24]
[ 42 135  31 172]
[165 190  14 178]
[145 197  32 184]
[  6 120 146 102]
[101  13 195 204]


O iterador **WHILE** usamos quando queremos repetir código sem saber de antemão quando este deve ser interrompido. Ele será finalizado quando alguma condição for satisfeita.

Deve-se tomar cuidado em não escrever um **WHILE** infinito. Você terá que cancelar a execução do código para pará-lo.

In [ ]:
contador = 0
while True:
    contador = contador + 1
    print(contador*2)
    if contador == 10:
        break

2
4
6
8
10
12
14
16
18
20


In [ ]:
contador = 0
while contador < 10:
    contador = contador + 1
    print(contador*2)

2
4
6
8
10
12
14
16
18
20


Utilização do comando **break** para interromper o loop.

Exemplo de um **while** infinito

In [ ]:
while True:
    print('Python é legal demais!')

O **while** também aceita o comando **else** no após o seu fim. Algo para executar após o break acontecer.

In [ ]:
i = 1
while i <= 10:
    print(i * '*')
    i += 1
else:
    print('*')

*
**
***
****
*****
******
*******
********
*********
**********
*
